#
# Repo with the Dockerfile:
#
services:
  comfyui:
    build:
      context: .
      args:
        COMFYUI_REF: v0.15.0
    image: comfyui-gfx1151:v0.15.0
    container_name: comfyui-gfx1151
    restart: always
    shm_size: 8G
    volumes:
      - ./ComfyUI/models:/opt/ComfyUI/models
      - ./ComfyUI/input:/opt/ComfyUI/input
      - ./ComfyUI/output:/opt/ComfyUI/output
      - ./ComfyUI/user:/opt/ComfyUI/user
    environment:
      - TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1
      - HSA_OVERRIDE_GFX_VERSION=11.5.1
      - HSA_ENABLE_SDMA=0
      - HSA_USE_SVM=0
      - HIP_VISIBLE_DEVICES=0
      - PYTORCH_ALLOC_CONF=expandable_segments:True,garbage_collection_threshold:0.8
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
      - render
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

